### ISSUE TITLE
Calling Workspace.createFromTemplate via JS api 2 times results in dup-model error

### ISSUE THREAD

**Issue by kraman** [strongloop/loopback-workspace#302] opened 2016-07-16 00:31 UTC
When calling https://github.com/strongloop/loopback-workspace/blob/master/common/models/workspace.js#L363 with the notes template via JS API,
it seems like some model information is being cached. We get an error 

`The 'ModelConfig' instance is not valid. 'name' is not unique (value: "User").`

**Comment by chandadharap** [comment] 2016-07-16 00:44
Assigned to Candy. We need this fixed for code freeze on Monday 7/18/16. Affect Multi-project UX 5030 feature. @jtary and @kraman FYI.

Reference:
https://github.ibm.com/apimesh/scrum-platform-foundation/issues/1257

**Comment by bajtos** [comment] 2016-07-18 08:51
@0candy 

> I am trying to reset the workspace after createFromTemplate but I don’t think that’s the right way to fix it. (edited)
> Should this be supported on the workspace side or should workspace be reset in apic after every loopback project is created?

IMO, we should fix `loadWorkspace` (added by https://github.com/strongloop/loopback-workspace/pull/240) to to reset the internal state when WORKSPACE_DIR is changed.

I think the implementation we use in tests, where we delete all workspace models instances before changing the project directory, may not work here - I would expect that such delete would trigger save operation and thus the project files will be emptied as a result. It's not a problem in tests, because `resetWorkspace` is usually called after all files from the project dir were removed.

It is crucial to add a unit-test reproducing the current issue, to ensure we understand correctly the problem and to prevent regressions in the future.

Things to watch out for: after a new project is loaded,
 - The old project should remain intact, i.e. no project files are changed as the result of switch.
 - The new project is not touched, i.e. no project files are changes as the result of switch. This does not matter when creating a new project, but it's important when switching between two existing projects.

**Comment by bajtos** [comment] 2016-07-18 08:53
Once `loadWorkspace` is fixed, we should rework unit-test to use `loadWorkspace` instead of test-provided `resetWorkspace`. That may help us to uncover further edge cases to fix. However, I think it's ok to leave that as the second step, out of scope of the urgent fix.

**Closed** 2016-07-19 20:21 UTC
Labels: API Connect, bug, major
