### ISSUE TITLE
loopback-connector not installed when creating lb app

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-workspace#487] opened 2017-04-19 15:23 UTC
# Description/Steps to reproduce
When using `lb` cmd to create a lb3 app, there is a warning saying the `loopback-connector` is not installed.
```
npm WARN loopback-datasource-juggler@3.5.5 requires a peer of loopback-connector@^4.0.0 but none was installed.
```

To reproduce: 
```
? What's the name of your application? diana-test
? Enter name of the directory to contain the project: diana-test
   create diana-test/
     info change the working directory to diana-test

? Which version of LoopBack would you like to use? 3.x (current)
? What kind of application do you have in mind? hello-world (A project containing a controller, including a single vanilla Message and
 a single remote method)
```

I'm using `master (http://apiconnect01.rchland.ibm.com:4873)` as `sl-registry`.  Problem doesn't exists if I use `default (https://registry.npmjs.org/)`. 
If I remember correctly, this problem only appears today (April 19).

# Expected result
- [ ] No warning message after creating a lb app
- [ ] loopback-connector@4 is installed

This is true if I'm using `https://registry.npmjs.org/`

cc @loay

**Comment by raymondfeng** [comment] 2017-04-19 15:47
I think it's caused by https://github.com/strongloop/loopback-datasource-juggler/pull/1326.

@ssh24 @bobbysmith007 This is problematic as by default, the juggler and mem connector doesn't require `loopback-connector` at all. The peer dependency is only valid if other connectors are installed.

**Comment by bobbysmith007** [comment] 2017-04-19 16:07
I'm sorry, definitely didn't want to compound dependency problems :/ 

I was hoping this would just be a case of moving that dependency up one level in the hierarchy (so that whatever depended on loopback-datasource-juggler, would also depend on loopback-connector. This seemed sensible as loopback-datasource-juggler and the various loopback-connector-* libraries are trying to share object models between each other and loopback-connector and therefore this  seemed like something that would accommodate that behavior.

EG: It would seem like Connector objects (kv-memory, memory, and transient connectors) should share the same type as the connectors from eg: loopback-postgres-connector).  It would also seem that Transactions from datasource-juggler, should share the same type as transactions from any of the other connectors.

Apologies and do feel free revert that if you disagree with that analysis.  I really only got into trouble with this while debugging and trying to target specific objects and their reported types (with the same name from the same lib) not being reference equal.

**Comment by ssh24** [comment] 2017-04-19 16:14
@raymondfeng I did not notice that we do not install `loopback-connector` by default when creating a lb app. Should we revert https://github.com/strongloop/loopback-datasource-juggler/pull/1326 or do a PR to install `loopback-connector` as a part of all the dependency installation?

**Comment by dhmlau** [comment] 2017-04-19 17:04
@ssh24 , we do install `loopback-connector` by default when creating a lb app.  But using the latest code, it doesn't because of the warning.

**Comment by bobbysmith007** [comment] 2017-04-19 17:10
Is this a dependency ordering thing then (eg: `loopback-connector` should be listed before `loopback-datasource-juggler`)?

https://github.com/strongloop/loopback/blob/master/package.json seems to not have `loopback-connector` listed, but perhaps I misunderstood.

**Comment by ssh24** [comment] 2017-04-19 17:14
@dhmlau I don't think `loopback-connector` is installed by default. Created a test app with the dependencies installing by itself. Here is how my node_modules look like after installing using from master:
```
sakibs-mac:lb-workspace-issue-486 ssh$ ls node_modules/ | grep loopback
eslint-config-loopback
loopback
loopback-boot
loopback-component-explorer
loopback-connector-remote
loopback-datasource-juggler
loopback-datatype-geopoint
loopback-phase
loopback-swagger
```

**Comment by raymondfeng** [comment] 2017-04-19 17:19
@ssh24 I think we should revert the PR for now before we figure out a better way. Making `loopback-connector` a default dependency for generated LB app is not ideal.

**Comment by bobbysmith007** [comment] 2017-04-19 17:26
Isn't `loopback-connector` *already* a dependency of `loopback` (because it will be a dependency of `loopback-datasource-juggler` which is a dependency `loopback`).  AFAICT this only moves loopback-connector up one level in the dependency chain and shouldnt be adding any new dependencies.

**Comment by dhmlau** [comment] 2017-04-19 18:06
@ssh24  FYI - If i use `https://registry.npmjs.org/` to create the lb app, `loopback-connector` is installed.  But if using master, then it was not installed.

**Comment by ssh24** [comment] 2017-04-19 18:10
@dhmlau That is because this patch was not released to npmjs yet.

**Comment by ssh24** [comment] 2017-04-19 18:49
Closing this as the two reverted PR have been landed. The error should be fixed on the master registry.

**Closed by ssh24** 2017-04-19 18:49 UTC
Labels: #in-progress, apex

**Comment by bobbysmith007** [comment] 2017-04-19 18:56
@raymondfeng If you have a moment could you please explain why: "Making loopback-connector a default dependency for generated LB app is not ideal." 

As regards my previous comment:
> Isn't loopback-connector already a dependency of loopback (because it will be a dependency of loopback-datasource-juggler which is a dependency loopback). AFAICT this only moves loopback-connector up one level in the dependency chain and shouldnt be adding any new dependencies.

Thanks!
